export declare const PAGINATION_LIMIT = 100;
export declare const REQUIRED_LABEL = "obrigat\u00F3rio";
export declare const INVALID_FORMAT = "formato inv\u00E1lido";
export declare const KEYTYPES: string[];
export declare const ACCOUNTTYPES: string[];
export declare const CpfCnpjRegex: RegExp;
export declare const PhoneRegex: RegExp;
export declare const CepRegex: RegExp;
export declare const DateRegex: RegExp;
export declare const HourRegex: RegExp;
